name: net
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # https://pub.dev/packages/dio
  dio: ^5.4.3+1
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.3
  # https://pub.dev/packages/get
  get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

